/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <STM32f103xx_RCC_driver.h>
#include <STM32f103xx_GPIO_driver.h>
#include <STM32f103xx_EXTI_driver.h>
#include <STM32f103xx_NVIC_driver.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void wait_ms(uint32_t time)
{
	uint32_t i , j;
	for(i=0 ; i<time ; i++)
		for(j=0;j<500;j++);
}
void clock_init(void)
{
	RCC_enuInitConfig();
	GPIOA_PERI_CLOCK_ENABLE();
	GPIOB_PERI_CLOCK_ENABLE();
}
void GPIO_init(void)
{
	GPIO_Handle_t PIN_Config;
	PIN_Config.PGPIOx = GPIOA;
	PIN_Config.GPIO_PinConfig_t.GPIO_PinMode = GPIO_MODE_OUTPUT_PP;
	PIN_Config.GPIO_PinConfig_t.GPIO_PinNumber = GPIO_PIN_1;
	PIN_Config.GPIO_PinConfig_t.GPIO_PinSpeed = GPIO_SPEED_2M;
	GPIO_enuInit(&PIN_Config);

	PIN_Config.PGPIOx = GPIOB;
	PIN_Config.GPIO_PinConfig_t.GPIO_PinMode = GPIO_MODE_INPUT_FLO;
	PIN_Config.GPIO_PinConfig_t.GPIO_PinNumber = GPIO_PIN_1;
	GPIO_enuInit(&PIN_Config);
}
void EXTI_init(void)
{
	EXTI_Config_t EXTI_Config;
	EXTI_Config.EXTI_PportNumber  = GPIOB;
	EXTI_Config.EXTI_u8LineNumber = EXTI_LINE_1;
	EXTI_Config.EXTI_u8TriggerMode = EXTI_TRIGGER_RISHING;
	EXTI_enuInitConfig(&EXTI_Config);
}
void Toggle(void);
int main(void)
{
	clock_init();
	GPIO_init();
	EXTI_init();
	MNVIC_enuEnableInterrupt(Interrupt_EXTI1);
	while(1)
	{
		EXTI1_enuCallBack(Toggle);
	}

}
void Toggle(void)
{
	GPIO_enuToggleOutputPin(GPIOA, GPIO_PIN_1);
}

